<?php
$form->setAttribute('action', $form_action);
$form->prepare();

echo $this->form()->openTag($form);

$submits = [];
$hidden = [];

foreach ($form->getElements() as $element)
{
    $element_type = $element->getAttribute("type");
    if ( $element_type === "submit" )
    {
        $submits[] = $element;
    }
    elseif ( $element_type === "hidden" )
    {
        $hidden[] = $element;
    }
    else
    {
        $error_class = count($element->getMessages()) > 0 ? "has-error" : "";
        ?><div class="form-group <?= $error_class ?>">
            <?= $this->formLabel($element) ?>
            <?= $this->formElement($element) ?>
            <?php if ( $element->hasAttribute("help-text") ): ?>
                <small class="form-text text-muted">
                    <?= $element->getAttribute("help-text") ?>
                </small>
            <?php endif; ?>
            <?= $this->formElementErrors()->render($element, ['class' => 'help-block']) ?>
        </div><?php
    }
}

foreach ($submits as $submit)
{
    echo $this->formSubmit($submit);
}

if ( isset($cancelURL) )
{
    ?><a href="<?= $cancelURL ?>" class="btn btn-default">Cancel</a><?php
}

foreach ($hidden as $hid)
{
    echo $this->formHidden($hid);
}

echo $this->form()->closeTag();
